# WebSocket Close Codes
CLOSE_CODE_UNAUTHORIZED = 4001
CLOSE_CODE_FORBIDDEN = 4003
CLOSE_CODE_NOT_FOUND = 4004

# Error Codes
ERROR_EMPTY_MESSAGE = "EMPTY_MESSAGE"
ERROR_INVALID_FORMAT = "INVALID_FORMAT"

# Message Limits
MAX_MESSAGE_LENGTH = 10000

# Sync Limits
MAX_SYNC_MESSAGES = 100
