# Generated by Django 5.2.9 on 2026-01-04 11:34

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_pg_trgm_extension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content'], name='message_content_trigram_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
