# Generated by Django 5.2.9 on 2026-01-04 22:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_add_message_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='message_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', '-created_at'], name='message_room_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['updated_at'], name='room_updated_at_idx'),
        ),
    ]
